version: '3.6'
services:
  db:
    image: mysql:8.0
    container_name: DB
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=melp
      - MYSQL_PASSWORD=1234 # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./DB:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  web:
    container_name: WEB
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: PHPMYADMIN_Web
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
