services:
  db:
    image: mysql:8.0
    container_name: DB
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=melp
      - MYSQL_ROOT_PASSWORD=iloveyou
      - MYSQL_PASSWORD=I@Admin*123456 # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=0 # equivalent to True
    volumes:
      - "./DB:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  web:
    container_name: WEB
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - DB_DATABASE=web
      - DB_USER=melp
      - DB_PASSWORD=I@Admin*123456
      - DB_HOST=db
    volumes:
      - "./src/WEB:/var/www/html"
    ports:
      - 80:80
    # ADD host kibana and elasticsearch to file /etc/host to config SSL/TLS and fix error 
    extra_hosts:
      - "kibana.local:192.168.56.101"
      - "elasticsearch.local:192.168.56.101"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: PHPMYADMIN_Web
    ports:
      - 81:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
