version: '3.6'
services:
  db:
    image: mysql:latest
    container_name: DB
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=melp
      - MYSQL_ROOT_PASSWORD=pinkguy
      - MYSQL_PASSWORD=fvcked # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=0 # equivalent to True
    volumes:
      - "./DB:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  web:
    container_name: WEB
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHP_myadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
